# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jumper < Formula
  desc "Jumper is a simple CLI SSH manager"
  homepage "https://github.com/jklaiber/jumper"
  version "0.1.0"
  license "GPL-3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jklaiber/jumper/releases/download/v0.1.0/jumper_0.1.0_darwin_arm64.tar.gz"
      sha256 "1c0eb70a3f5556c759a06af498a62ec529aae83468b07f67fdbe81d23b4a6746"

      def install
        bin.install "jumper"
        bash_completion.install "completions/jumper.bash" => "jumper"
        zsh_completion.install "completions/jumper.zsh" => "_jumper"
        fish_completion.install "completions/jumper.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jklaiber/jumper/releases/download/v0.1.0/jumper_0.1.0_darwin_amd64.tar.gz"
      sha256 "737edef4cfe696680dce03c2768f3aff741028d2de18ef232c71179c61ba4367"

      def install
        bin.install "jumper"
        bash_completion.install "completions/jumper.bash" => "jumper"
        zsh_completion.install "completions/jumper.zsh" => "_jumper"
        fish_completion.install "completions/jumper.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jklaiber/jumper/releases/download/v0.1.0/jumper_0.1.0_linux_arm64.tar.gz"
      sha256 "fbe94fd5a7970a2ab1daf074f068b770f671218f4f14d56b720f6cd0af6c9291"

      def install
        bin.install "jumper"
        bash_completion.install "completions/jumper.bash" => "jumper"
        zsh_completion.install "completions/jumper.zsh" => "_jumper"
        fish_completion.install "completions/jumper.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jklaiber/jumper/releases/download/v0.1.0/jumper_0.1.0_linux_amd64.tar.gz"
      sha256 "2d744438ad75b4646bc609d1a367a5223797c65b0fc70f423c08190f67715d34"

      def install
        bin.install "jumper"
        bash_completion.install "completions/jumper.bash" => "jumper"
        zsh_completion.install "completions/jumper.zsh" => "_jumper"
        fish_completion.install "completions/jumper.fish"
      end
    end
  end

  test do
    system "#{bin}/jumper version"
  end
end
